config/routes.rb
Mytwitter::Application.routes.draw do
  get "microposts/create"

  get "microposts/destroy"

  get "static_pages/home"

  get "static_pages/about"

  resources :users
  resources :sessions,only: [:new,:create,:destroy]

  resources :microposts do
    resources :comments
  end
  
  resources :users do
    member do
      get :following,:followers
    end
  end

  
  resources :relationships, only: [:create,:destroy]
  
  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy',via: :delete
  match "/about", to: 'static_pages#about'

  root :to => 'static_pages#home'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :content,:micropost_id,:user_id,:commentfrom_id,:commentto_id
  belongs_to :micropost
  default_scope order:'comments.created_at ASC'
  validates :micropost_id, presence: true
  validates :content, presence: true
end

app/models/micropost.rb
class Micropost < ActiveRecord::Base
	attr_accessible :content
	belongs_to :user
	has_many :comments, dependent: :destroy
	validates :user_id, presence: true
	validates :content, presence: true
	default_scope order: 'microposts.created_at DESC'
	
	def self.from_users_followed_by(user)
		followed_user_ids = "SELECT followed_id FROM relationships
		WHERE follower_id = :user_id"
		where("user_id IN (#{followed_user_ids}) OR user_id = :user_id",
			user_id: user.id)
	end
end

app/controllers/comments_controller.rb
#coding: utf-8
class CommentsController < ApplicationController


	def create
		@micropost = Micropost.find(params[:micropost_id])
		@comment = @micropost.comments.build(params[:comment])
		@comment.commentfrom_id = current_user.id
		if @comment.save
			redirect_to micropost_path(@micropost)
		else
		 flash[:notice] = "没什么可说的就别说了呗!"
          redirect_to micropost_path(@micropost)
		end
	end

	def destroy
		@micropost = Micropost.find_by_id(params[:micropost_id])
		@comment = Comment.find_by_id(params[:id])
		@comment.destroy
		redirect_to micropost_path(@micropost)
	end
	
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<li>
	
	<% for i in 0...@micropost.comment_ids.length %>
	<% if @micropost.comment_ids[i] == comment.id %>
	<% i  %>
	<% comment_ownner =  User.find_by_id(comment.commentfrom_id) %>
	<%= link_to gravatar_for(comment_ownner,size: 52), comment_ownner %>#<%= i+1 %>楼
	<% end %>
	<% end %>
	<span class="user">
		<%= link_to comment_ownner.name, comment_ownner %>
	</span>
	<span class="content"><%= comment.content %></span>
	<span class="timestamp">
		回复于 <%= comment.created_at %>距今已有<%= time_ago_in_words(comment.created_at) %>		
	</span>

	<% if current_user?(comment_ownner) %>
	<%= link_to "删除", [@micropost,comment], method: :delete,
	data: { confirm: "You sure?" },
	title: comment.content %>
	<% end %>

</li>