config/routes.rb
Mytwitter::Application.routes.draw do
  get "microposts/create"

  get "microposts/destroy"

  get "static_pages/home"

  get "static_pages/about"

  resources :users
  resources :sessions,only: [:new,:create,:destroy]

  resources :microposts do
    resources :comments
  end
  
  resources :users do
    member do
      get :following,:followers
    end
  end

  
  resources :relationships, only: [:create,:destroy]
  
  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy',via: :delete
  match "/about", to: 'static_pages#about'

  root :to => 'static_pages#home'

end

app/views/shared/_comment_form.html.erb
<%= form_for [@micropost,@comment] do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
  	<% i= current_user.name %>
    <%= f.text_area :content, placeholder:  "#{i} , 回复点什么..." %>
  </div>
  <%= f.submit "提交", class: "btn btn-large btn-primary" %>
<% end %>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <ol class="microposts">
    <%= render partial: 'shared/feed_item', collection: @feed_items %>
  </ol>
  <%= will_paginate @feed_items %>
<% end %>

app/views/shared/_feed_item.html.erb
<li id="<%= feed_item.id %>">
	<%= link_to gravatar_for(feed_item.user,size: 52), feed_item.user %>
	<span class="user">
		<%= link_to feed_item.user.name, feed_item.user %>
	</span>
	<span class="content"><%= feed_item.content %></span>
	<span class="timestamp">
		发表于 <%= feed_item.created_at %>距今已有<%= time_ago_in_words(feed_item.created_at) %>	<strong><%= feed_item.comments.count %>条</strong><%= link_to "回复",feed_item %>
	</span>

	<% if current_user?(feed_item.user) %>
	<%= link_to "删除", feed_item, method: :delete,
	data: { confirm: "You sure?" },
	title: feed_item.content %>
	<% end %>
</li>

app/views/shared/_micropost_form.html.erb
<%= form_for(@micropost) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
  	<% i= current_user.name %>
    <%= f.text_area :content, placeholder: "#{i} ， 说点什么..." %>
  </div>
  <%= f.submit "提交", class: "btn btn-large btn-primary" %>
<% end %>

app/views/shared/_sign_in.html.erb
<form accept-charset="UTF-8" action="/sessions" method="post">
  <div>
    <label for="session_email">邮箱</label>
    <input id="session_email" name="session[email]" size="30" type="text" />
  </div>
  <div>
    <label for="session_password">密码</label>
    <input id="session_password" name="session[password]" size="30"
    type="password" />
  </div>
  <input class="btn  btn-primary" name="commit" type="submit"
  value="登录" />
</form>
<div class="">
 <a href="signup" class="btn btn-primary">没注册不让进</a>
 <%= image_tag("cui.png",class: "profile img-circle loading", width: "70") %>
 </div>

</div>

app/views/shared/_sign_in_modal.html.erb
<div class="modal hide" id="signinModal">
	<div class="modal-header">
		<button type="button" class="close" data-dismiss="modal">x</button>
		<h3><%= image_tag("littletwitter.jpg",class: "profile img-circle loading", width: "30") %></h3>
	</div>

	<div class="modal-body">

		<%= render "shared/sign_in" %>
	</div>
</div>

app/views/shared/_sign_up_modal.html.erb
<div class="modal hide" id="signupModal">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal">x</button>
    <h3><%= image_tag("littletwitter.jpg",class: "profile img-circle loading", width: "40") %></h3>
  </div>
  <div class="modal-body">


   <form accept-charset="UTF-8" action="/users" class="new_user"
      id="new_user" method="post">

  <label for="user_name">昵称</label>
  <input id="user_name" name="user[name]" size="30" type="text" />

  <label for="user_email">邮箱</label>
  <input id="user_email" name="user[email]" size="30" type="text" />

  <label for="user_password">密码</label>
  <input id="user_password" name="user[password]" size="30"
         type="password" />

  <label for="user_password_confirmation">确认</label>
  <input id="user_password_confirmation"
         name="user[password_confirmation]" size="30" type="password" />

  <input class="btn btn-large btn-large btn-primary" name="commit" type="submit"
         value="注册" />
</form>

  </div>
  <div class="modal-footer">
    <%= image_tag("hua.png",class: "profile img-circle loading", width: "80") %>&nbsp;瞄了个眯，又茫然了，好像注册过了?
    <a href="signin" class="btn btn-primary">登录</a>
  </div>
</div>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
	<a href="<%= following_user_path(@user) %>">
		<strong id="following" class="stat">
			<%= @user.followed_users.count %>
		</strong>
		关注
	</a>
	<a href="<%= followers_user_path(@user) %>">
		<strong id ="followers" class="stat">
			<%= @user.followers.count %>
		</strong>
		被关注
	</a>
</div>

app/views/shared/_user_info.html.erb
<a href="<%= user_path(current_user) %>">
  <%= gravatar_for current_user, size: 60 %>
</a>
<h1>
  <%= current_user.name %>
</h1>
<span>
  <%= link_to "我的页面", current_user %>
</span>
<span>
  <%= current_user.microposts.count %>条记录
</span>