config/routes.rb
Mytwitter::Application.routes.draw do
  get "microposts/create"

  get "microposts/destroy"

  get "static_pages/home"

  get "static_pages/about"

  resources :users
  resources :sessions,only: [:new,:create,:destroy]

  resources :microposts do
    resources :comments
  end
  
  resources :users do
    member do
      get :following,:followers
    end
  end

  
  resources :relationships, only: [:create,:destroy]
  
  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy',via: :delete
  match "/about", to: 'static_pages#about'

  root :to => 'static_pages#home'

end

app/views/layouts/_footer.html.erb
<div class="navbar">
  <div class="navbar-inner">
    <div class="container">
      <footer class="footer">
        <small>
          <%= link_to image_tag("github 108.jpg", width: "50",alt: "github"), 'http://github.com/lafmad' %>
        </small>
        <nav>
          <ul class="nav nav-inverse pull-right ">
            <li><a href="http://lafmad.github.io/">blog</a></li>
             <%= link_to image_tag("hua.png",class: "profile img-circle loading", width: "50",alt:"关于"), about_path %>
          </ul>
        </nav>
      </footer>
    </div>
  </div>
</div>

app/views/layouts/_header.html.erb
<div id="navbar" class="navbar navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">

      <ul class="nav pull-left">
       <%= image_tag("littletwitter.jpg",class: "profile img-circle loading", width: "30") %>
     </ul>

     <ul class="nav">
      <li class="active"><a href="#">不知</a></li>
      <li><a href="#">说些</a></li>
      <li><a href="#">什么</a></li>
      <li><a href="#">才好</a></li>
    </ul>

    <ul class="nav pull-right">
      <li><%= link_to "主页",root_path %></li>
      <% if signed_in? %>
      <li><%= link_to "用户", users_path %></li>
      <li id="fat-menu" class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
          账户 <b class="caret"></b>
        </a>
        <ul class="dropdown-menu">
          <li><%= link_to "个人页面", current_user %></li>
          <li><%= link_to "更改设置", edit_user_path(current_user) %></li>
          <li class="divider"></li>
          <li>
            <%= link_to "退出", signout_path, method: "delete" %>
          </li>
        </ul>
      </li>
    </ul>

    <% else %>
    <a class="btn btn-primary  btn-inverse" data-toggle="modal" href="#signinModal" >登录</a>
    <% end %>
  </div>



</div>
</div>
<%= render 'shared/sign_in_modal' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="zh-CN" manifest="cache.manifest">
<head>
	<title><%= full_title(yield(:title)) %></title>
	<%= stylesheet_link_tag    "application", :media => "all" %>
	<%= javascript_include_tag "application" %>
	<%= csrf_meta_tags %>
	<!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
</head>
<body>
<%= render 'layouts/header' %>
 <div class="container">
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
<%= yield %>
<%= render 'layouts/footer' %>
<%= debug(params) if Rails.env.development? %>
</body>
</html>